### ISSUE TITLE
Support decimal numbers (e.g. 0.5; .3;)

### ISSUE THREAD

**Issue by jalexanderqed** [UCSB-CS56-Projects/cs56-utilities-grapher#13]
Currently, the code hangs if a decimal number is given as input to one of the custom functions. Make sure these are fully supported. Not that both "0.5" and ".5" should be considered valid

**Comment by jalexanderqed** [comment]
F16 OK (50 pts)

**Comment by YunSuk** [comment]
It is currently supported
