### ISSUE TITLE
Add support for arbitrary parenthesized expressions

### ISSUE THREAD

**Issue by jalexanderqed** [UCSB-CS56-Projects/cs56-utilities-grapher#17]
Expressions accepted should include sin, cos, logs, and powers. This will require writing a parser for such expressions, which is fairly difficult but not unmanageable. Feel free to ask for help. Not that your parser AND evaluator should include appropriate error handling (e.g. when you do not recognize a string or a negative is passed to a logarithm). You should also add support for some basic constants like PI and e. Note that this should support BOTH decimal and integer values.

**Comment by jalexanderqed** [comment]
F16 OK (500 pts)

**Comment by YunSuk** [comment]
It is currently supported
